version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 6.0
  pre_build:
    commands:
      - echo Restore started on `date`
      - cd ConsolePipelineRepository
      - dotnet restore
  build:
    commands:
      - echo Build started on `date`
      - cd ConsolePipelineRepository
      - dotnet build --configuration Release
  post_build:
    commands:
      - echo Publish started on `date`
      - cd ConsolePipelineRepository
      - dotnet publish --configuration Release --output ./publish
artifacts:
  files:
    - 'ConsolePipelineRepository/publish/**/*'
  base-directory: 'ConsolePipelineRepository'
